server:
  servlet:
    session:
      cookie:
        name: MYCOOKIEID
      #here i can give any name for the cookie
      
      
spring:
  zipkin:
    base-url: http://localhost:9411/


security:
    #disables the default secuirty beascause we config one for us
   oauth2:
    client:
      clientId: ClientId  #here we must give the client id that we define it in server side
      clientSecret: secret  #here we must give the client secert that we define it in server side
      access-token-validity-seconds: 3600  #my token validate for one hour
      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
      accessTokenUri: http://localhost:8089/auth/oauth/token #the server side were we define the token to make user take token
      userAuthorizationUri: http://localhost:8089/auth/oauth/authorize #were the auth in server side
 #   sso:
 #    login-path: http://localhost:8089/auth/loginout
    resource:
      #userInfoUri: http://localhost:8089/auth/rest/hello/principal   #the end point in the server   //I think is the principal url
      userInfoUri: http://localhost:8089/auth/principal
      
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      